CSEngine: CSE::SRenderGroup Class Reference
CSE::SRenderGroup Class Reference abstract
Public Member Functions
SRenderGroup (const RenderMgr &renderMgr)
virtual void RegisterObject (SIRender *object)=0
virtual void RemoveObjects (SIRender *object)=0
virtual void RenderAll (const CameraBase &camera) const =0
virtual void Exterminate ()=0
Static Protected Member Functions
static void BindSourceBuffer (const SFrameBuffer &buffer, const GLProgramHandle &handle, int layout)
Protected Attributes
const RenderMgr * m_renderMgr
Detailed Description
Definition at line 7 of file SRenderGroup.h.
Constructor & Destructor Documentation
SRenderGroup()
CSE::SRenderGroup::SRenderGroup (const RenderMgr & renderMgr) inline
Definition at line 9 of file SRenderGroup.h.
: m_renderMgr(&renderMgr) {}
Member Function Documentation
BindSourceBuffer()
void SRenderGroup::BindSourceBuffer (const SFrameBuffer & buffer, const GLProgramHandle & handle, int layout) static protected
렌더링 직전의 소스 버퍼를 바인딩 하는 함수입니다.
Parameters
buffer 바인딩 할 SFrameBuffer를 지정합니다.
handle SourceBuffer의 uniform id입니다.
Definition at line 10 of file SRenderGroup.cpp.
{
    const auto& srcBufferTexture = buffer.GetMainColorTexture();
    const auto& uniforms = handle.Uniforms;
    const auto& size = buffer.GetSize();
    const float sizeRaw[2] = { static_cast<float>(size.x), static_cast<float>(size.y) };
    if(srcBufferTexture == nullptr) return;
    if(uniforms.SourceBuffer >= 0)
        srcBufferTexture->Bind(uniforms.SourceBuffer, layout);
    if(uniforms.SourceBufferSize >= 0)
        glUniform2fv(uniforms.SourceBufferSize, 1, sizeRaw);
}
References CSE::SFrameBuffer::GetMainColorTexture().
Referenced by CSE::ForwardRenderGroup::RenderAll(), and CSE::DeferredRenderGroup::RenderGbuffer().
Exterminate()
virtual void CSE::SRenderGroup::Exterminate () pure virtual
Implemented in CSE::DeferredRenderGroup, CSE::DepthOnlyRenderGroup, and CSE::ForwardRenderGroup.
RegisterObject()
virtual void CSE::SRenderGroup::RegisterObject (SIRender * object) pure virtual
Implemented in CSE::DeferredRenderGroup, CSE::DepthOnlyRenderGroup, and CSE::ForwardRenderGroup.
RemoveObjects()
virtual void CSE::SRenderGroup::RemoveObjects (SIRender * object) pure virtual
Implemented in CSE::DeferredRenderGroup, CSE::DepthOnlyRenderGroup, and CSE::ForwardRenderGroup.
RenderAll()
virtual void CSE::SRenderGroup::RenderAll (const CameraBase & camera) const pure virtual
Implemented in CSE::DeferredRenderGroup, CSE::DepthOnlyRenderGroup, and CSE::ForwardRenderGroup.
Member Data Documentation
m_renderMgr
const RenderMgr* CSE::SRenderGroup::m_renderMgr protected
Definition at line 29 of file SRenderGroup.h.
The documentation for this class was generated from the following files:
Util/Render/SRenderGroup.h
Util/Render/SRenderGroup.cpp