CSEngine: CSE::LightMgr Class Reference
CSE::LightMgr Class Reference
#include <LightMgr.h>
Public Member Functions
LightMgr ()
~LightMgr () override
void AttachLightToShader (const GLProgramHandle *handle) const
void AttachLightMapToShader (const GLProgramHandle *handle, int textureLayout) const
void Init () override
int GetShadowCount () const
int GetLightMapCount () const
void RefreshShadowCount (int shadowCount=-1) const
Public Member Functions inherited from CSE::SContainerList< LightComponent * >
void Register (LightComponent * object) override
void Remove (LightComponent * object) override
LightComponent * Get (int index) const override
std::list< LightComponent * > GetAll () const override
int GetID (LightComponent * object) const override
int GetSize () const override
Public Member Functions inherited from CSE::SIContainer< S, T, M >
virtual void Register (T object)=0
virtual void Remove (T object)=0
virtual T Get (M index) const =0
virtual S GetAll () const =0
virtual M GetID (T object) const =0
virtual int GetSize () const =0
Public Member Functions inherited from CSE::CoreBase
virtual void Init ()=0
virtual void Update (float elapsedTime)
Public Attributes
const int SHADOW_WIDTH = 1024
Width of the shadow map.
const int SHADOW_HEIGHT = 1024
Height of the shadow map.
Static Public Attributes
static constexpr float SHADOW_DISTANCE = 10.f
Distance of the shadow map.
Additional Inherited Members
Protected Attributes inherited from CSE::SContainerList< LightComponent * >
std::list< LightComponent * > m_objects
int m_size
Detailed Description
LightMgr class is a manager of Light components. This class also manages ShadowMap for giving shadow effects to objects in the scene.
Definition at line 17 of file LightMgr.h.
Constructor & Destructor Documentation
LightMgr()
LightMgr::LightMgr () explicit default
Constructor of LightMgr.
~LightMgr()
LightMgr::~LightMgr () override
Destructor of LightMgr.
Definition at line 10 of file LightMgr.cpp.
                    {
    SAFE_DELETE(m_environmentMgr);
}
Member Function Documentation
AttachLightMapToShader()
void LightMgr::AttachLightMapToShader (const GLProgramHandle * handle, int textureLayout) const
Attach the light map to the shader.
Parameters
handle Shader handle
textureLayout Layout of the texture
Definition at line 47 of file LightMgr.cpp.
{
    m_environmentMgr->BindPBREnvironmentMap(handle, textureLayout);
}
Referenced by CSE::DeferredRenderGroup::RenderGbuffer().
AttachLightToShader()
void LightMgr::AttachLightToShader (const GLProgramHandle * handle) const
Attach the light components to the shader.
Parameters
handle Shader handle
Definition at line 15 of file LightMgr.cpp.
{
    if (handle == nullptr) return;
    int index = 0;
    int shadow_index = 0;
    for (const auto& light : m_objects) {
        if (light == nullptr || !light->GetIsEnable()) continue;
        const auto& lightObject = light->GetLight();
        const auto& position = (light->m_type == LightComponent::DIRECTIONAL)
                               ? lightObject->direction
                               : vec4(*lightObject->position, 1.0f);
        glUniform4f(handle->Uniforms.LightPosition + index,
                    position.x, position.y, position.z, (light->m_type == LightComponent::DIRECTIONAL) ? 0.0f : 1.0f);
        glUniform3f(handle->Uniforms.LightColor + index, lightObject->color.x, lightObject->color.y, lightObject->color.z);
        glUniform1i(handle->Uniforms.LightType + index, light->m_type);
        if (handle->Uniforms.LightRadius >= 0)
            glUniform1f(handle->Uniforms.LightRadius + index, lightObject->radius);
        // Shadow
        auto isShadow = light->IsShadow();
        glUniform1i(handle->Uniforms.LightShadowMode + index, isShadow ? 1 : 0);
        light->BindShadow(*handle, index, shadow_index);
        if (isShadow) ++shadow_index;
        ++index;
    }
    if (index <= 0) return;
    glUniform1i(handle->Uniforms.LightSize, (int)m_objects.size());
}
Referenced by CSE::ForwardRenderGroup::RenderAll(), and CSE::DeferredRenderGroup::RenderGbuffer().
GetLightMapCount()
int CSE::LightMgr::GetLightMapCount () const inline
Get the light map count.
Returns
Light map count
Definition at line 64 of file LightMgr.h.
{
            return m_lightMapCount;
        }
Referenced by CSE::ForwardRenderGroup::RenderAll(), and CSE::DeferredRenderGroup::RenderGbuffer().
GetShadowCount()
int CSE::LightMgr::GetShadowCount () const inline
Get the shadow count.
Returns
Shadow count
Definition at line 56 of file LightMgr.h.
{
            return m_shadowCount;
        }
Referenced by CSE::ForwardRenderGroup::RenderAll(), and CSE::DeferredRenderGroup::RenderGbuffer().
Init()
void LightMgr::Init () override virtual
Initialize the LightMgr.
Implements CSE::CoreBase.
Definition at line 51 of file LightMgr.cpp.
                    {
    // Setting PBS Environment
    m_environmentMgr = new SEnvironmentMgr();
    m_environmentMgr->RenderPBREnvironment();
}
RefreshShadowCount()
void LightMgr::RefreshShadowCount (int shadowCount = -1) const
Refresh the shadow count.
Parameters
shadowCount Shadow count to refresh. Default is -1.
Definition at line 57 of file LightMgr.cpp.
{
    if(shadowCount < 0) {
        int tempCount = 0;
        for (const auto& light : m_objects) {
            ++tempCount;
        }
        m_shadowCount = tempCount;
        return;
    }
    m_shadowCount = shadowCount;
}
Member Data Documentation
SHADOW_DISTANCE
constexpr float CSE::LightMgr::SHADOW_DISTANCE = 10.f static constexpr
Distance of the shadow map.
Definition at line 21 of file LightMgr.h.
Referenced by CSE::DepthOnlyRenderGroup::RenderAll().
SHADOW_HEIGHT
const int CSE::LightMgr::SHADOW_HEIGHT = 1024
Height of the shadow map.
Definition at line 20 of file LightMgr.h.
SHADOW_WIDTH
const int CSE::LightMgr::SHADOW_WIDTH = 1024
Width of the shadow map.
Definition at line 19 of file LightMgr.h.
The documentation for this class was generated from the following files:
Manager/LightMgr.h
Manager/LightMgr.cpp