CSEngine: CSE::RenderMgr Class Reference
CSE::RenderMgr Class Reference
Class for managing rendering operations.
#include <RenderMgr.h>
Public Member Functions
RenderMgr ()
Constructor for RenderMgr.
void Init () override
Initialization of resources required for rendering.
void SetViewport ()
Modify the framebuffer to fit the modified screen size.
void Render () const override
Rendering all stuffs.
unsigned int * GetWidth () const
Get the width of the screen.
unsigned int * GetHeight () const
Get the height of the screen.
Public Member Functions inherited from CSE::RenderContainer
void Register (SIRender *object, RenderGroupMode groupMode)
void Remove (SIRender *object, RenderGroupMode groupFlag)
Public Member Functions inherited from CSE::CoreBufferContainer
SFrameBuffer * GetMainBuffer () const
Public Member Functions inherited from CSE::CoreBase
virtual void Init ()=0
virtual void Update (float elapsedTime)
virtual void Render () const =0
Protected Member Functions
void Exterminate () override
Destroy all resources used for rendering.
virtual void Exterminate ()
Protected Member Functions inherited from CSE::CoreBufferContainer
void InitBuffers (int width, int height)
void ResizeBuffers (int width, int height)
Additional Inherited Members
Public Types inherited from CSE::RenderContainer
enum RenderGroupMode { FORWARD = 0 , DEFERRED = 1 , DEPTH_ONLY = 2 }
Protected Attributes inherited from CSE::RenderContainer
SRenderGroup * m_forwardRenderGroup = nullptr
SRenderGroup * m_deferredRenderGroup = nullptr
SRenderGroup * m_depthOnlyRenderGroup = nullptr
unsigned int * m_width = nullptr
unsigned int * m_height = nullptr
Detailed Description
Class for managing rendering operations.
This class is responsible for managing all elements involved in the rendering operation, including cameras, buffers, etc.
Definition at line 21 of file RenderMgr.h.
Constructor & Destructor Documentation
~RenderMgr()
RenderMgr::~RenderMgr () override
Definition at line 23 of file RenderMgr.cpp.
                      {
    Exterminate();
}
Member Function Documentation
Exterminate()
void RenderMgr::Exterminate () override protected virtual
Destroy all resources used for rendering.
Reimplemented from CSE::RenderContainer.
Definition at line 96 of file RenderMgr.cpp.
{
    RenderContainer::Exterminate();
}
GetHeight()
unsigned int * CSE::RenderMgr::GetHeight () const inline
Get the height of the screen.
Returns
Pointer to the height of the screen.
Definition at line 59 of file RenderMgr.h.
{
            return m_height;
        }
Referenced by CSE::DeferredRenderGroup::DeferredRenderGroup().
GetWidth()
unsigned int * CSE::RenderMgr::GetWidth () const inline
Get the width of the screen.
Returns
Pointer to the width of the screen.
Definition at line 50 of file RenderMgr.h.
{
            return m_width;
        }
Referenced by CSE::DeferredRenderGroup::DeferredRenderGroup().
Init()
void RenderMgr::Init () override virtual
Initialization of resources required for rendering.
Implements CSE::CoreBase.
Definition at line 27 of file RenderMgr.cpp.
                     {
    cameraMgr = CORE->GetCore(CameraMgr);
    lightMgr = CORE->GetCore(LightMgr);
    m_width = SEnvironmentMgr::GetPointerWidth();
    m_height = SEnvironmentMgr::GetPointerHeight();
    InitBuffers((int)*m_width, (int)*m_height);
    m_forwardRenderGroup = new ForwardRenderGroup(*this);
    m_deferredRenderGroup = new DeferredRenderGroup(*this);
    m_depthOnlyRenderGroup = new DepthOnlyRenderGroup(*this);
}
Render()
void RenderMgr::Render () const override virtual
Rendering all stuffs.
Implements CSE::RenderCoreBase.
Definition at line 47 of file RenderMgr.cpp.
{
    // 1. Render depth buffer for shadows.
    RenderShadows();
    // 2. Render active sub cameras.
    RenderSubCameras();
    // 3. Main Render Buffer
    RenderMainCamera();
}
SetViewport()
void RenderMgr::SetViewport ()
Modify the framebuffer to fit the modified screen size.
Attention
This is a function that can have a big impact on performance.
Definition at line 41 of file RenderMgr.cpp.
{
    if(m_deferredRenderGroup != nullptr)
        static_cast<DeferredRenderGroup*>(m_deferredRenderGroup)->SetViewport();
    ResizeBuffers((int)*m_width, (int)*m_height);
}
References SetViewport().
Referenced by SetViewport().
The documentation for this class was generated from the following files:
Manager/Render/RenderMgr.h
Manager/Render/RenderMgr.cpp