CSEngine: CSE::SFrameBuffer Class Reference
CSE::SFrameBuffer Class Reference
#include <SFrameBuffer.h>
Public Types
enum BufferType { RENDER = 0 , DEPTH = 1 , STENCIL = 2 }
enum BufferDimension { PLANE = 0 , CUBE = 1 }
enum BufferStatus { NONE = 0 , COLOR_ONLY = 1 , DEPTH_ONLY = 2 , MULTI = 3 }
enum BlitType { IN_ORDER = 0 , REVERSE = 1 }
Public Member Functions
void GenerateFramebuffer (BufferDimension dimension, int width, int height)
unsigned int GenerateRenderbuffer (BufferType type, int internalFormat)
STexture * GenerateTexturebuffer (BufferType type, int channel, int level=0)
void RasterizeFramebuffer ()
void AttachCubeBuffer (int index, int level=0) const
void AttachFrameBuffer (int target=GL_FRAMEBUFFER) const
void DetachFrameBuffer () const
void ResizeFrameBuffer (int width, int height)
void Exterminate () override
void BlitFrameBuffer (const SFrameBuffer &dst, BlitType type=IN_ORDER)
int GetWidth () const
int GetHeight () const
const ivec2 & GetSize () const
BufferStatus GetBufferStatus () const
STexture * GetTexture (int index) const
STexture * GetTexture (const char *id) const
unsigned int GetRenderbufferID (int index) const
STexture * GetMainColorTexture () const
STexture * GetDepthTexture () const
Public Member Functions inherited from CSE::SResource
SResource (bool isRegister)
SResource (const SResource *resource, bool isRegister)
void SetName (std::string name)
void SetID (std::string id)
std::string GetName () const
std::string GetID () const
void LinkResource (AssetMgr::AssetReference *asset)
void LinkResource (std::string name)
Public Member Functions inherited from CSE::SObject
SObject (bool isRegister)
virtual void Exterminate ()=0
virtual void SetUndestroyable (bool enable)
virtual void Destroy ()
virtual void __FORCE_DESTROY__ ()
Protected Member Functions
void Init (const AssetMgr::AssetReference *asset) override
virtual void Init (const AssetMgr::AssetReference *asset)=0
Additional Inherited Members
Static Public Member Functions inherited from CSE::SResource
template<class T >
static T * Create (const std::string &name, bool isForceCreate=false)
template<class T >
static T * Create (const AssetMgr::AssetReference *asset, bool isForceCreate=false)
template<class T >
static T * Get (std::string name)
Detailed Description
See also
To use the SFrameBuffer class, you need to follow the steps below:
Generate a framebuffer.
m_frameBuffer->GenerateFramebuffer(SFrameBuffer::PLANE);
Generate buffers.
m_frameBuffer->GenerateTexturebuffer(SFrameBuffer::DEPTH, width, height, GL_DEPTH_COMPONENT);
Rasterize the framebuffer.
m_frameBuffer->RasterizeFramebuffer();
Definition at line 30 of file SFrameBuffer.h.
Member Enumeration Documentation
BlitType
enum CSE::SFrameBuffer::BlitType
Definition at line 41 of file SFrameBuffer.h.
                      {
            IN_ORDER = 0, REVERSE = 1,
        };
BufferDimension
enum CSE::SFrameBuffer::BufferDimension
Definition at line 35 of file SFrameBuffer.h.
{
            PLANE = 0, CUBE = 1,
        };
BufferStatus
enum CSE::SFrameBuffer::BufferStatus
Definition at line 38 of file SFrameBuffer.h.
{
            NONE = 0, COLOR_ONLY = 1, DEPTH_ONLY = 2, MULTI = 3,
        };
BufferType
enum CSE::SFrameBuffer::BufferType
Definition at line 32 of file SFrameBuffer.h.
{
            RENDER = 0, DEPTH = 1, STENCIL = 2,
        };
Constructor & Destructor Documentation
SFrameBuffer()
SFrameBuffer::SFrameBuffer ()
Definition at line 31 of file SFrameBuffer.cpp.
{
    SetUndestroyable(true);
}
Member Function Documentation
AttachCubeBuffer()
void SFrameBuffer::AttachCubeBuffer (int index, int level = 0) const
Definition at line 188 of file SFrameBuffer.cpp.
{
    if (m_dimension != CUBE) return;
    for (const auto& buffer : m_buffers) {
        const auto& texture = buffer->texture;
        if (texture == nullptr) continue;
        glFramebufferTexture2D(GL_FRAMEBUFFER, GenerateAttachmentType(buffer->type, false),
                               GL_TEXTURE_CUBE_MAP_POSITIVE_X + index, texture->GetTextureID(), level);
    }
}
AttachFrameBuffer()
void SFrameBuffer::AttachFrameBuffer (int target = GL_FRAMEBUFFER) const
Definition at line 199 of file SFrameBuffer.cpp.
{
    glViewport(0, 0, m_size->x, m_size->y);
    glBindFramebuffer(target, m_fbo);
}
BlitFrameBuffer()
void SFrameBuffer::BlitFrameBuffer (const SFrameBuffer & dst, BlitType type = IN_ORDER)
Safely blit the framebuffer. Each framebuffer must be in BufferType::MULTI state, and all buffers must be in the form of STexture. For blit techniques that are not suitable for that condition, it is faster to use glBlitFramebuffer.
Note
The format of the framebuffer should be organized in the following order:
[0] = Color Buffer
[1] = Depth Buffer
Parameters
dst The framebuffer to merge.
type Determine the order in which they will be merged. Default is IN_ORDER.
Definition at line 234 of file SFrameBuffer.cpp.
{
    if (m_mainColorBuffer == nullptr || m_depthBuffer == nullptr) {
        Exterminate();
        GenerateFramebuffer(PLANE, m_size->x, m_size->y);
        GenerateTexturebuffer(RENDER, GL_RGB);
        GenerateTexturebuffer(DEPTH, GL_DEPTH_COMPONENT);
        RasterizeFramebuffer();
    }
    const SFrameBuffer* a;
    const SFrameBuffer* b;
    if (type == REVERSE) {
        a = this;
        b = &dst;
    } else {
        a = &dst;
        b = this;
    }
    const auto& aColorTexture = a->m_mainColorBuffer->texture;
    const auto& bColorTexture = b->m_mainColorBuffer->texture;
    const auto& aDepthTexture = a->m_depthBuffer->texture;
    const auto& bDepthTexture = b->m_depthBuffer->texture;
    if (m_blitObject.handle == nullptr) {
        m_blitObject.handle = SResource::Create<GLProgramHandle>(Settings::GetDefaultBlitBufferShaderID());
        m_blitObject.aColor = m_blitObject.handle->UniformLocation("a.color")->id;
        m_blitObject.bColor = m_blitObject.handle->UniformLocation("b.color")->id;
        m_blitObject.aDepth = m_blitObject.handle->UniformLocation("a.depth")->id;
        m_blitObject.bDepth = m_blitObject.handle->UniformLocation("b.depth")->id;
    }
    AttachFrameBuffer();
    glViewport(0, 0, m_size->x, m_size->y);
    glUseProgram(m_blitObject.handle->Program);
    aColorTexture->Bind(m_blitObject.aColor, 0);
    bColorTexture->Bind(m_blitObject.bColor, 1);
    aDepthTexture->Bind(m_blitObject.aDepth, 2);
    bDepthTexture->Bind(m_blitObject.bDepth, 3);
    ShaderUtil::BindAttributeToPlane();
}
References GenerateFramebuffer(), GenerateTexturebuffer(), and RasterizeFramebuffer().
DetachFrameBuffer()
void SFrameBuffer::DetachFrameBuffer () const
Definition at line 204 of file SFrameBuffer.cpp.
{
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
}
Exterminate()
void SFrameBuffer::Exterminate () override virtual
Implements CSE::SObject.
Definition at line 37 of file SFrameBuffer.cpp.
{
    glDeleteFramebuffers(1, &m_fbo);
    for (const auto& buffer : m_buffers) {
        ReleaseBufferObject(buffer);
    }
    m_buffers.clear();
    m_depthBuffer = m_mainColorBuffer = nullptr;
    SAFE_DELETE(m_size);
}
GenerateFramebuffer()
void SFrameBuffer::GenerateFramebuffer (BufferDimension dimension, int width, int height)
This is the first function called when creating a framebuffer. You specify the dimensions of the framebuffer through that function.
Parameters
dimension Sets the dimensions of the framebuffer. The default is SFrameBuffer::PLANE.
width Write the width of the render buffer.
height Writes the height of the render buffer.
Definition at line 104 of file SFrameBuffer.cpp.
{
    m_dimension = dimension;
    m_size->x = width;
    m_size->y = height;
    glGenFramebuffers(1, &m_fbo);
    glBindFramebuffer(GL_FRAMEBUFFER, m_fbo);
}
Referenced by BlitFrameBuffer().
GenerateRenderbuffer()
unsigned int SFrameBuffer::GenerateRenderbuffer (BufferType type, int internalFormat)
Creates a render buffer in a non-texture format.
Parameters
type Specifies the type of buffer to create. The default is RENDER.
internalFormat Sets the internal format for the render buffer. Format details can be found at this link.
Returns
Returns the ID value of the created render buffer. If creation fails, 0 is returned.
Definition at line 113 of file SFrameBuffer.cpp.
{
    if (m_dimension == CUBE) return 0;
    auto buffer = new BufferObject();
    buffer->type = type;
    buffer->format = internalFormat;
    glGenRenderbuffers(1, &buffer->renderbufferId);
    glBindRenderbuffer(GL_RENDERBUFFER, buffer->renderbufferId);
    glRenderbufferStorage(GL_RENDERBUFFER, GenerateInternalFormat(internalFormat), m_size->x, m_size->y);
    glBindFramebuffer(GL_FRAMEBUFFER, m_fbo);
    glFramebufferRenderbuffer(GL_FRAMEBUFFER, GenerateAttachmentType(type, false), GL_RENDERBUFFER,
                              buffer->renderbufferId);
    if (type == RENDER) {
        if (m_mainColorBuffer == nullptr)
            m_mainColorBuffer = buffer;
    } else if (m_depthBuffer == nullptr) {
        m_depthBuffer = buffer;
    }
    m_buffers.push_back(buffer);
    return buffer->renderbufferId;
}
GenerateTexturebuffer()
STexture * SFrameBuffer::GenerateTexturebuffer (BufferType type, int channel, int level = 0)
Creates a render buffer in texture format.
Parameters
type Specifies the type of buffer to create. The default is RENDER.
channel Sets the channel format for the render buffer. Format details can be found at this link.
level Sets the texture mipmap level. Default is 0.
Returns
Returns the STexture of the created render texture buffer. If creation fails, nullptr is returned.
Definition at line 138 of file SFrameBuffer.cpp.
{
    auto buffer = new BufferObject();
    buffer->type = type;
    buffer->format = channel;
    buffer->level = (short) level;
    buffer->texture = new STexture(static_cast<STexture::Type>(m_dimension));
    buffer->texture->InitTexture(m_size->x, m_size->y, channel, GenerateInternalFormat(channel),
                                 GenerateInternalType(channel));
    unsigned int texId = buffer->texture->GetTextureID();
//    if(level > 0)
    glBindFramebuffer(GL_FRAMEBUFFER, m_fbo);
    if (m_dimension == PLANE) {
        glFramebufferTexture2D(GL_FRAMEBUFFER, GenerateAttachmentType(type), GL_TEXTURE_2D, texId, level);
    } else {
        // TODO:
        GenerateAttachmentType(buffer->type, false);
    }
    if (type == RENDER) {
        if (m_mainColorBuffer == nullptr)
            m_mainColorBuffer = buffer;
    } else if (m_depthBuffer == nullptr) {
        m_depthBuffer = buffer;
    }
    m_buffers.push_back(buffer);
    return buffer->texture;
}
Referenced by BlitFrameBuffer(), and RasterizeFramebuffer().
GetBufferStatus()
SFrameBuffer::BufferStatus SFrameBuffer::GetBufferStatus () const
Definition at line 343 of file SFrameBuffer.cpp.
{
    return m_bufferStatus;
}
GetDepthTexture()
STexture * CSE::SFrameBuffer::GetDepthTexture () const inline
Get the texture assigned to the framebuffer as depth.
Returns
if the corresponding index is an invalid texture type, nullptr is returned.
Definition at line 165 of file SFrameBuffer.h.
{
            if (m_depthBuffer == nullptr) return nullptr;
            return m_depthBuffer->texture;
        }
GetHeight()
int SFrameBuffer::GetHeight () const
Definition at line 280 of file SFrameBuffer.cpp.
{
    return m_size->y;
}
GetMainColorTexture()
STexture * CSE::SFrameBuffer::GetMainColorTexture () const inline
Get the texture assigned to the framebuffer as GL_COLOR_ATTACHMENT0.
Returns
if the corresponding index is an invalid texture type, nullptr is returned.
Definition at line 156 of file SFrameBuffer.h.
{
            if (m_mainColorBuffer == nullptr) return nullptr;
            return m_mainColorBuffer->texture;
        }
Referenced by CSE::SRenderGroup::BindSourceBuffer().
GetRenderbufferID()
unsigned int SFrameBuffer::GetRenderbufferID (int index) const
Get renderbuffer ID that exist in the framebuffer.
Parameters
index buffer index in framebuffer
Returns
if the corresponding index is an invalid buffer ID, 0 is returned.
Definition at line 365 of file SFrameBuffer.cpp.
{
    if (index < 0 || index > m_buffers.size() - 1) return 0;
    auto id = m_buffers[index]->renderbufferId;
    return id;
}
GetSize()
const ivec2 & CSE::SFrameBuffer::GetSize () const inline
Definition at line 125 of file SFrameBuffer.h.
{
            return *m_size;
        }
GetTexture() [1/2]
STexture * SFrameBuffer::GetTexture (const char * id) const
Get textures that exist in the framebuffer.
Parameters
id texture id in framebuffer
Returns
if the corresponding index is an invalid texture type, nullptr is returned.
Definition at line 354 of file SFrameBuffer.cpp.
{
    for (const auto& buffer : m_buffers) {
        const auto& texture = buffer->texture;
        if (texture == nullptr) continue;
        std::string bufferId = texture->GetID();
        if (bufferId == id) return texture;
    }
    return nullptr;
}
GetTexture() [2/2]
STexture * SFrameBuffer::GetTexture (int index) const
Get textures that exist in the framebuffer.
Parameters
index buffer index in framebuffer
Returns
if the corresponding index is an invalid texture type, nullptr is returned.
Definition at line 347 of file SFrameBuffer.cpp.
{
    if (index < 0 || index > m_buffers.size() - 1) return nullptr;
    auto texture = m_buffers[index]->texture;
    return texture;
}
GetWidth()
int SFrameBuffer::GetWidth () const
Definition at line 276 of file SFrameBuffer.cpp.
{
    return m_size->x;
}
Init()
void SFrameBuffer::Init (const AssetMgr::AssetReference * asset) override protected virtual
Implements CSE::SResource.
Definition at line 49 of file SFrameBuffer.cpp.
{
    const XNode* root = nullptr;
    try {
        root = XFILE(asset->path.c_str()).getRoot();
    }
    catch (int e) {
        SAFE_DELETE(root);
        return;
    }
    try {
        const XNode& cse_framebuffer = root->getChild("CSEFRAMEBUFFER");
        const XNode& info = cse_framebuffer.getChild("info");
        auto width_str = info.getAttribute("width").value;
        auto height_str = info.getAttribute("height").value;
        auto dimension_str = info.getAttribute("dimension").value;
        m_size->x = std::stoi(width_str);
        m_size->y = std::stoi(height_str);
        auto dimension = static_cast<BufferDimension>(std::stoi(dimension_str));
        GenerateFramebuffer(dimension, m_size->x, m_size->y);
        const XNode& buffers = cse_framebuffer.getChild("buffers");
        int index = 0;
        for (const auto& buffer_node : buffers.children) {
            auto type_str = buffer_node.getAttribute("type").value;
            auto format_str = buffer_node.getAttribute("format").value;
            auto isTexture_str = buffer_node.getAttribute("isTexture").value;
            auto type = static_cast<BufferType>(std::stoi(type_str));
            auto format = std::stoi(format_str);
            auto isTexture = std::stoi(isTexture_str) == 1;
            if (isTexture) {
                const auto& texture = GenerateTexturebuffer(type, format);
                const auto& textureName = "?Texture" + std::to_string(index);
                texture->SetName(GetName() + textureName);
                texture->SetID(GetID() + textureName);
            } else {
                GenerateRenderbuffer(type, format);
            }
            ++index;
        }
        RasterizeFramebuffer();
    }
    catch (int e) {
        SAFE_DELETE(root);
        auto resMgr = CORE->GetCore(ResMgr);
        resMgr->Remove(this);
    }
    SAFE_DELETE(root);
}
RasterizeFramebuffer()
void SFrameBuffer::RasterizeFramebuffer ()
Create all the render buffers to allocate to the framebuffer and proceed with rasterization. You can use the framebuffer after calling the function.
Definition at line 168 of file SFrameBuffer.cpp.
{
    glBindFramebuffer(GL_FRAMEBUFFER, m_fbo);
    m_buffers.reserve(m_buffers.size());
    // tell OpenGL which color attachments we'll use (of this framebuffer) for rendering
    if (m_colorAttachmentSize > 1) {
        std::vector<unsigned int> attachments;
        attachments.reserve(m_colorAttachmentSize);
        for (int i = 0; i < m_colorAttachmentSize; ++i) {
            attachments.push_back(GL_COLOR_ATTACHMENT0 + i);
        }
        glDrawBuffers(m_colorAttachmentSize, &attachments[0]);
    }
    if (m_bufferStatus == COLOR_ONLY) {
        GenerateTexturebuffer(SFrameBuffer::DEPTH, GL_DEPTH_COMPONENT);
        m_bufferStatus = MULTI;
    }
}
References GenerateTexturebuffer().
Referenced by BlitFrameBuffer().
ResizeFrameBuffer()
void SFrameBuffer::ResizeFrameBuffer (int width, int height)
Definition at line 208 of file SFrameBuffer.cpp.
{
    std::vector<BufferObject*> origBufferVector(m_buffers);
    m_buffers.clear();
    m_buffers.reserve(origBufferVector.size());
    m_colorAttachmentSize = 0;
    glDeleteFramebuffers(1, &m_fbo);
    GenerateFramebuffer(m_dimension, width, height);
    m_depthBuffer = m_mainColorBuffer = nullptr;
    for (const auto& buffer : origBufferVector) {
        auto type = buffer->type;
        auto format = buffer->format;
        auto level = buffer->level;
        auto isTexture = buffer->texture != nullptr;
        ReleaseBufferObject(buffer);
        if (isTexture)
            GenerateTexturebuffer(type, format, level);
        else
            GenerateRenderbuffer(type, format);
    }
    RasterizeFramebuffer();
}
The documentation for this class was generated from the following files:
Util/Render/SFrameBuffer.h
Util/Render/SFrameBuffer.cpp